### PR TITLE
Add Red Hat Eng and IT CA certs

### PR DESCRIPTION
**Pull request by amisstea**
This is necessary for tox to install dependencies from internal Red
Hat git repos.

### CODE REVIEW

**Review by haripate — APPROVED** [review]
LGTM

**Comment by mmalina** [comment]
Is this really a good idea? First, it's internal, so I don't think it should be part of this public repo/image. And second, hardcoding this into the repo means that it's bound to break one day. Why not fetch the cert before running tox in gitlab ci or whatever you use?

Also, proposing a change in a widely used image on a Friday afternoon and then merging minutes later before anybody can even comment is not very nice.

**Comment by amisstea** [comment]
@mmalina this should be a safe change to make as all it does is add a couple trusted CA certs. It's necessary to unblock some of our internal CI/CD pipelines today. These are public CA certs so they shouldn't need to be protected either. We could try to install the them dynamically in our gitlab pipelines but this is a solution everyone can benefit from and the certs have a very distant expiration date (2055). FWIW this isn't the first PR to request this (see #13) and I reached out to the scaffolding guild master for the recommendation.

**Comment by mmalina** [comment]
@amisstea thanks for the additional details. Good to know you talked to Adam. I understand that CA certs are not considered private, but they are only related to internal Red Hat resources, so I still think that it's not optimal to have them included in a public github repo. But I guess others have a different opinion, so fine with me.

**Comment by amisstea** [comment]
Thanks for the tip @twaugh! We may have to use that since the quay.io builds for this repo are failing anyway :frowning_face:. More details are available in ISV-1964.

**Pull request merged**
