### PR TITLE
Add gcc-c++

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by ralphbean** [comment]
@Allda can you kindly provide review and merge?

Triggered from https://gitlab.cee.redhat.com/exd/catalog/-/merge_requests/3347

**Review by Allda — APPROVED** [review]

**Comment by twaugh** [comment]
This changes doesn't seem to have made it into the `latest` image yet. Does the image build need re-prodding?

**Comment by Allda** [comment]
@twaugh The code change caused the build to fail. I re-triggered the build several times with always the same result. I also tried to rebuild other branches in this repo and it passed so I guess it is somehow related to this PR.

Here is the error from build logs:
```
[91mErrors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
[0m"
```
Looks like DNS issue to me so I am confused why this code change caused the build to fail.

**Comment by twaugh** [comment]
After writing the last comment I investigated further. It turns out that we do not need gcc-c++ after all -- we'd been trying to 'pip install' from within tox, and incorrectly had basepython=python3.9 for that environment. Changing that fixed the package installation.

You can revert this change.

**Pull request merged**
