### PR TITLE
Add pandoc.

### PR DESCRIPTION
**Pull request by ralphbean**
For tox processes that manipulate documentation.

### CODE REVIEW

**Comment by cit1zen** [comment]
+1

**Comment by ralphbean** [comment]
I don't have rights here to merge.

What is the policy?  Is one +1 sufficient, or do we need two?

**Comment by csomh** [comment]
Hm, hm, I have the weird feeling that by adding more and tools in this image, we might end up having a difficult to maintain monster.

:-1: for now. Let's discuss why adding these packages is needed, and if they are other ways to avoid this?

**Comment by csomh** [comment]
To clarify the above comment:

Is `pandoc` and `lua` a dependency for some Python package installed from PyPI during test runs, similar to the `*-devel` packages already in the image? Or they are intended for standalone usage, i.e called as a command  by tox.

If the later, would it be possible to prepare a standalone image for these tools? (Like it was done for [markdownlint](https://github.com/redhat-aqe/markdownlint-container).)

**Comment by ralphbean** [comment]
A standalone image like markdownlint would work fine.  I can set to work on that.

I want to use [pypandoc](https://pypi.org/project/pypandoc/) which just calls out to pandoc under the hood, which in turn uses lua to load an additional plugin.

**Pull request closed without merging**
